import { Amplify } from 'aws-amplify';

// In a real AWS environment, this file is automatically generated by the Amplify CLI 
// as `aws-exports.js` or `amplifyconfiguration.json`. 
// For this rebuild, we are mocking the structure to allow seamless integration 
// once you run `amplify init` and `amplify add auth/api/storage`.

const awsConfig = {
  Auth: {
    Cognito: {
      userPoolId: process.env.NEXT_PUBLIC_USER_POOL_ID || 'REGION_XXXXX',
      userPoolClientId: process.env.NEXT_PUBLIC_USER_POOL_CLIENT_ID || 'XXXXX',
      identityPoolId: process.env.NEXT_PUBLIC_IDENTITY_POOL_ID || 'REGION:XXXXX',
    }
  },
  API: {
    GraphQL: {
      endpoint: process.env.NEXT_PUBLIC_APPSYNC_ENDPOINT || 'https://xxxxxx.appsync-api.region.amazonaws.com/graphql',
      region: process.env.NEXT_PUBLIC_AWS_REGION || 'us-east-1',
      defaultAuthMode: 'userPool' as const
    },
    REST: {
      // For invoking AWS Bedrock / AI endpoints via API Gateway
      BedrockAPI: {
        endpoint: process.env.NEXT_PUBLIC_API_GATEWAY_URL || 'https://xxxxxx.execute-api.region.amazonaws.com/dev',
        region: process.env.NEXT_PUBLIC_AWS_REGION || 'us-east-1',
      }
    }
  },
  Storage: {
    S3: {
      bucket: process.env.NEXT_PUBLIC_S3_BUCKET || 'vannate-assets',
      region: process.env.NEXT_PUBLIC_AWS_REGION || 'us-east-1',
    }
  }
};

Amplify.configure(awsConfig as any);

export default awsConfig;
